default_stages: [pre-commit]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        args: [--config-file=pyproject.toml]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
    -   id: ruff
        args: [--config=pyproject.toml, --fix]
    -   id: ruff-format
        args: [--config=pyproject.toml]

-   repo: local
    hooks:
    -   id: pytest
        name: Run pytest
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false

default_language_version:
  python: python3.12
